const OnboardingEntity = require('../../models/OnboardingEntity');
const PracticeClient = require('../../models/PracticeClient');
const { hasModuleLevel } = require('../../config/modules');
const cmSvc = require('./service');
const {
  gatesFor,
  totalSlaFor,
  findGate,
  findItem,
  NEW_GATES,
  RENEWAL_GATES,
  PACKAGES,
  DAY_MS,
} = require('./onboarding.constants');

function gateStartMap(doc) {
  if (!doc.gateStart) return {};
  if (doc.gateStart instanceof Map) return Object.fromEntries(doc.gateStart);
  return { ...doc.gateStart };
}

function entityPlain(doc) {
  const o = doc.toObject ? doc.toObject() : { ...doc };
  o.gateStart = gateStartMap(o);
  o.id = String(o._id);
  return o;
}

function fmtD(t) {
  if (!t) return '—';
  return new Date(t).toLocaleDateString('en-AU', { day: '2-digit', month: 'short', year: 'numeric' });
}

function actorName(user) {
  return user?.name || user?.email || 'System';
}

function canEditOnboarding(user) {
  return hasModuleLevel(user, 'cm-onboarding', 'edit');
}

function itemDone(entity, item) {
  if (item.triCheck) return entity.tri?.asic && entity.tri?.abr && entity.tri?.ato;
  if (item.noteField) {
    return (
      entity.done.includes(item.id) &&
      String(entity.notes?.[item.noteField] || '').trim().length >= 15
    );
  }
  return entity.done.includes(item.id);
}

function gateComplete(entity, gate) {
  return gate.items.every((it) => itemDone(entity, it));
}

function currentGate(entity) {
  for (const g of gatesFor(entity)) {
    if (!gateComplete(entity, g)) return g;
  }
  return null;
}

function slaState(entity) {
  const g = currentGate(entity);
  if (!g) return null;
  const starts = gateStartMap(entity);
  const start = starts[g.id] ? new Date(starts[g.id]).getTime() : new Date(entity.createdAt).getTime();
  const left = g.sla - (Date.now() - start) / DAY_MS;
  return { gate: g, left, overdue: left < 0 };
}

function buildHandoverPack(entity) {
  const gates = gatesFor(entity);
  const starts = gateStartMap(entity);
  const gateLines = gates
    .map((g) => {
      const cleared = gateComplete(entity, g);
      const start = starts[g.id];
      return `  Gate ${g.num} — ${g.name} (${g.owner}): ${cleared ? 'CLEARED' : 'INCOMPLETE'}${start ? ` · started ${fmtD(start)}` : ''}`;
    })
    .join('\n');
  const tri = `  ASIC ${entity.tri?.asic ? 'OK' : 'X'} · ABR ${entity.tri?.abr ? 'OK' : 'X'} · ATO ${entity.tri?.ato ? 'OK' : 'X'}`;
  const rejections = (entity.log || [])
    .filter((l) => l.text.startsWith('HANDOVER REJECTED'))
    .map((l) => `  ${fmtD(l.at)} — ${l.text}`)
    .join('\n');
  const created = new Date(entity.createdAt).getTime();
  const completed = entity.completedAt ? new Date(entity.completedAt).getTime() : null;
  const days = completed
    ? ((completed - created) / DAY_MS).toFixed(1)
    : '—';
  const contact = entity.contact || {};
  return [
    `NANAK ACCOUNTANTS — ${entity.track === 'renewal' ? 'RENEWAL RE-VERIFICATION PACK' : 'CLIENT HANDOVER PACK'}`,
    '============================================',
    `Entity:          ${entity.name}`,
    `Track:           ${entity.track === 'renewal' ? 'Renewal (existing client)' : 'New client'}`,
    `Package:         ${entity.pkg}`,
    `Client manager:  ${entity.managerName}`,
    `Contact:         ${contact.person || '—'} · ${contact.phone || 'no phone'} · ${contact.email || 'no email'}`,
    `Processed:       ${fmtD(entity.createdAt)} → ${entity.completedAt ? fmtD(entity.completedAt) : 'in progress'} (${days} days, target ${totalSlaFor(entity)})`,
    '',
    'GATE HISTORY',
    gateLines,
    '',
    'ADDRESS INTEGRITY (registered address verified across registries)',
    tri,
    '',
    'BUSINESS BACKGROUND',
    `  ${entity.notes?.background || '(not recorded)'}`,
    '',
    'ATO POSITION',
    `  ${entity.notes?.atoPosition || '(not recorded)'}`,
    rejections ? `\nREJECTION HISTORY\n${rejections}` : '',
    '',
    '— Generated by Onboarding Gate Board. Paste into CRM client notes.',
  ].join('\n');
}

function enrichEntity(doc) {
  const e = entityPlain(doc);
  const cur = currentGate(e);
  const sla = e.status === 'active' ? slaState(e) : null;
  return {
    ...e,
    currentGate: cur,
    sla,
    totalSla: totalSlaFor(e),
  };
}

function pushLog(entity, text) {
  entity.log.unshift({ text, at: new Date() });
}

function afterChange(entity, gate, text) {
  const xg = gatesFor(entity);
  pushLog(entity, text);
  if (gateComplete(entity, gate)) {
    const next = xg.find((g) => g.num === gate.num + 1);
    if (next) {
      const starts = entity.gateStart instanceof Map ? entity.gateStart : new Map(Object.entries(entity.gateStart || {}));
      if (!starts.get(next.id)) {
        starts.set(next.id, new Date());
        entity.gateStart = starts;
        pushLog(
          entity,
          `Gate ${gate.num} cleared — Gate ${next.num} clock started (${next.sla}d SLA)`
        );
      }
    } else {
      entity.status = 'complete';
      entity.completedAt = new Date();
      entity.handoverPack = buildHandoverPack(entity);
      pushLog(
        entity,
        entity.track === 'renewal'
          ? `Renewal complete — re-verification pack filed to ${entity.managerName}'s client notes`
          : `Handover complete — pack filed to ${entity.managerName}'s client notes`
      );
    }
  }
}

async function fileHandoverToClient(entity, user) {
  if (!entity.practiceClientId || !entity.handoverPack) return;
  const client = await PracticeClient.findById(entity.practiceClientId);
  if (!client) return;
  const today = new Date().toLocaleDateString('en-AU', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
  const label =
    entity.track === 'renewal' ? 'Renewal re-verification pack' : 'Client handover pack';
  client.notes.unshift({
    type: 'info',
    text: `${label}\n\n${entity.handoverPack}`,
    author: actorName(user),
    date: today,
  });
  client.activity.unshift({
    date: today,
    who: actorName(user),
    action: `${label} filed from Onboarding Gate Board`,
  });
  await client.save();
}

async function getPriorBackground(practiceClientId) {
  if (!practiceClientId) return '';
  const prev = await OnboardingEntity.findOne({
    practiceClientId,
    status: 'complete',
  })
    .sort({ completedAt: -1 })
    .select('notes.background')
    .lean();
  return prev?.notes?.background || '';
}

async function getMeta(_user) {
  const managers = await cmSvc.listAssignableTeamMembers();
  return {
    newGates: NEW_GATES,
    renewalGates: RENEWAL_GATES,
    packages: PACKAGES,
    managers,
    structureTypes: PracticeClient.STRUCTURE_TYPES,
  };
}

async function getDashboard() {
  const entities = await OnboardingEntity.find().lean();
  const enriched = entities.map((e) => enrichEntity(e));
  const active = enriched.filter((e) => e.status === 'active');
  const overdue = active.filter((e) => e.sla?.overdue);
  const atHandover = active.filter((e) => e.currentGate?.handoverGate);
  const done = enriched.filter((e) => e.status === 'complete');
  return {
    inFlight: active.length,
    overdue: overdue.length,
    atHandover: atHandover.length,
    completed: done.length,
  };
}

async function listEntities(filter = 'active') {
  let entities;
  if (filter === 'done') {
    entities = await OnboardingEntity.find({ status: 'complete' }).sort({ completedAt: -1 });
  } else {
    entities = await OnboardingEntity.find({ status: 'active' }).sort({ createdAt: -1 });
    const enriched = entities.map((e) => enrichEntity(e));
    if (filter === 'overdue') {
      return enriched.filter((e) => e.sla?.overdue);
    }
    if (filter === 'handover') {
      return enriched.filter((e) => e.currentGate?.handoverGate);
    }
    return enriched;
  }
  return entities.map((e) => enrichEntity(e));
}

async function getEntity(id) {
  const doc = await OnboardingEntity.findById(id);
  if (!doc) {
    const err = new Error('Onboarding entity not found');
    err.statusCode = 404;
    throw err;
  }
  return enrichEntity(doc);
}

async function assertNoDuplicate(name, track) {
  const existing = await OnboardingEntity.findOne({
    name: new RegExp(`^${String(name).trim().replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`, 'i'),
    track,
    status: 'active',
  });
  if (existing) {
    const err = new Error(`Active ${track} onboarding already in progress for "${name}"`);
    err.statusCode = 409;
    throw err;
  }
}

async function createEntity(user, body) {
  if (!canEditOnboarding(user)) {
    const err = new Error('Edit access required');
    err.statusCode = 403;
    throw err;
  }

  const track = body.track === 'renewal' ? 'renewal' : 'new';
  let name = String(body.name || '').trim();
  let pkg = body.pkg || 'Company';
  let contact = body.contact || { person: '', phone: '', email: '' };
  let practiceClientId = body.practiceClientId || null;
  let notes = { background: '', atoPosition: '' };
  const firstGate = track === 'renewal' ? 'r1' : 'g1';
  const log = [];

  if (track === 'renewal') {
    if (!practiceClientId) {
      const err = new Error('practiceClientId required for renewal onboarding');
      err.statusCode = 400;
      throw err;
    }
    const pc = await PracticeClient.findById(practiceClientId);
    if (!pc) {
      const err = new Error('Practice client not found');
      err.statusCode = 404;
      throw err;
    }
    name = pc.entity;
    pkg = pc.type || pkg;
    contact = {
      person: contact.person || '',
      phone: contact.phone || pc.phone || '',
      email: contact.email || pc.email || '',
    };
    const priorBg = await getPriorBackground(practiceClientId);
    if (priorBg) notes.background = priorBg;
    log.push({
      text: 'Renewal opened from existing client record — background carried over',
      at: new Date(),
    });
  } else {
    if (!name) {
      const err = new Error('Entity name is required');
      err.statusCode = 400;
      throw err;
    }
    log.push({ text: `Entity created — package: ${pkg}`, at: new Date() });
  }

  await assertNoDuplicate(name, track);

  const resolved = await cmSvc.resolveManager(body.managerId, body.managerName);
  if (!resolved.managerName) {
    const err = new Error('Client manager is required');
    err.statusCode = 400;
    throw err;
  }

  const doc = await OnboardingEntity.create({
    name,
    track,
    pkg,
    managerId: resolved.managerId,
    managerName: resolved.managerName,
    practiceClientId,
    status: 'active',
    done: [],
    tri: { asic: false, abr: false, ato: false },
    gateStart: new Map([[firstGate, new Date()]]),
    contact,
    notes,
    handoverPack: '',
    log: log.length ? log : [{ text: track === 'renewal' ? 'Renewal opened' : 'Entity created', at: new Date() }],
    createdBy: user._id,
  });

  return enrichEntity(doc);
}

function gateForItem(entity, itemId) {
  const hit = findItem(entity, itemId);
  return hit?.gate || null;
}

function isItemEditable(entity, itemId) {
  if (entity.status === 'complete') return false;
  const cur = currentGate(entity);
  if (!cur) return false;
  const hit = findItem(entity, itemId);
  if (!hit) return false;
  return hit.gate.id === cur.id;
}

async function updateEntity(user, id, body) {
  if (!canEditOnboarding(user)) {
    const err = new Error('Edit access required');
    err.statusCode = 403;
    throw err;
  }

  const doc = await OnboardingEntity.findById(id);
  if (!doc) {
    const err = new Error('Onboarding entity not found');
    err.statusCode = 404;
    throw err;
  }

  const plain = entityPlain(doc);
  const wasComplete = doc.status === 'complete';

  if (body.contact) {
    doc.contact = {
      person: body.contact.person ?? doc.contact?.person ?? '',
      phone: body.contact.phone ?? doc.contact?.phone ?? '',
      email: body.contact.email ?? doc.contact?.email ?? '',
    };
  }

  if (body.notes) {
    const before = entityPlain(doc);
    const curBefore = currentGate(before);
    const wasComplete = curBefore ? gateComplete(before, curBefore) : true;
    doc.notes = {
      background: body.notes.background ?? doc.notes?.background ?? '',
      atoPosition: body.notes.atoPosition ?? doc.notes?.atoPosition ?? '',
    };
    if (doc.status !== 'complete' && curBefore && !wasComplete) {
      const after = entityPlain(doc);
      if (gateComplete(after, curBefore)) {
        afterChange(doc, curBefore, `Gate ${curBefore.num} cleared — notes completed`);
      }
    }
  }

  if (body.managerId !== undefined || body.managerName !== undefined) {
    const resolved = await cmSvc.resolveManager(
      body.managerId ?? doc.managerId,
      body.managerName ?? doc.managerName
    );
    if (String(resolved.managerName) !== String(doc.managerName)) {
      pushLog(doc, `Reallocated: client manager changed from ${doc.managerName} to ${resolved.managerName}`);
    }
    doc.managerId = resolved.managerId;
    doc.managerName = resolved.managerName;
    if (doc.status === 'complete') {
      doc.handoverPack = buildHandoverPack(entityPlain(doc));
    }
  }

  if (body.tri && doc.status !== 'complete') {
    const cur = currentGate(plain);
    if (!cur) {
      const err = new Error('No active gate');
      err.statusCode = 400;
      throw err;
    }
    const triItem = cur.items.find((i) => i.triCheck);
    if (!triItem || !isItemEditable(plain, triItem.id)) {
      const err = new Error('Tri-check not editable on current gate');
      err.statusCode = 400;
      throw err;
    }
    for (const k of ['asic', 'abr', 'ato']) {
      if (body.tri[k] !== undefined) {
        doc.tri[k] = !!body.tri[k];
        afterChange(
          doc,
          cur,
          `Address check — ${k.toUpperCase()} ${doc.tri[k] ? 'matched' : 'unmatched'}`
        );
      }
    }
  }

  if (body.toggleItem && doc.status !== 'complete') {
    const itemId = body.toggleItem;
    const hit = findItem(plain, itemId);
    if (!hit) {
      const err = new Error('Unknown checklist item');
      err.statusCode = 400;
      throw err;
    }
    if (!isItemEditable(plain, itemId)) {
      const err = new Error('Item not editable — complete the current gate first');
      err.statusCode = 400;
      throw err;
    }
    const has = doc.done.includes(itemId);
    doc.done = has ? doc.done.filter((d) => d !== itemId) : [...doc.done, itemId];
    afterChange(doc, hit.gate, `${has ? 'Unchecked' : 'Completed'}: ${hit.item.label}`);
  }

  await doc.save();

  const enriched = enrichEntity(doc);
  if (!wasComplete && doc.status === 'complete') {
    await fileHandoverToClient(doc, user);
  }

  return enriched;
}

async function searchClients(q) {
  const query = String(q || '').trim();
  if (query.length < 2) return [];
  const regex = new RegExp(query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i');
  const clients = await PracticeClient.find({
    status: 'Active',
    entity: regex,
  })
    .select('entity type managerName phone email')
    .limit(6)
    .lean();
  return clients.map((c) => ({
    id: String(c._id),
    name: c.entity,
    pkg: c.type,
    manager: c.managerName,
    contact: { person: '', phone: c.phone || '', email: c.email || '' },
  }));
}

async function getManagerFiles() {
  const done = await OnboardingEntity.find({ status: 'complete' }).sort({ completedAt: -1 });
  const inFlight = await OnboardingEntity.find({ status: 'active' });
  const managers = await cmSvc.listAssignableTeamMembers();
  const managerNames = managers.map((m) => m.name);

  const groups = managerNames
    .map((m) => ({
      manager: m,
      files: done.filter((e) => e.managerName === m).map((e) => enrichEntity(e)),
      inFlight: inFlight.filter((e) => e.managerName === m).length,
    }))
    .filter((g) => g.files.length || g.inFlight);

  // Include managers not in team list but with data
  const extraNames = [
    ...new Set([
      ...done.map((e) => e.managerName),
      ...inFlight.map((e) => e.managerName),
    ]),
  ].filter((n) => n && !managerNames.includes(n));

  for (const m of extraNames) {
    groups.push({
      manager: m,
      files: done.filter((e) => e.managerName === m).map((e) => enrichEntity(e)),
      inFlight: inFlight.filter((e) => e.managerName === m).length,
    });
  }

  return groups.sort((a, b) => a.manager.localeCompare(b.manager));
}

function allThrough(gateNum) {
  return NEW_GATES.filter((g) => g.num <= gateNum).flatMap((g) => g.items.map((i) => i.id));
}

async function seedOnboarding(user) {
  const count = await OnboardingEntity.countDocuments();
  if (count > 0) {
    const err = new Error('Onboarding data already exists');
    err.statusCode = 409;
    throw err;
  }

  const DAY = DAY_MS;
  const daysAgo = (n) => new Date(Date.now() - n * DAY);
  const managers = await cmSvc.listAssignableTeamMembers();
  const pick = (i) => managers[i % managers.length]?.name || 'Unassigned';

  const seeds = [
    {
      name: 'Harjit Transport Pty Ltd',
      track: 'new',
      pkg: 'Company',
      managerName: pick(0),
      createdAt: daysAgo(9),
      contact: {
        person: 'Harjit Singh',
        phone: '0421 884 220',
        email: 'harjit@harjittransport.com.au',
      },
      done: [...allThrough(2), 'g3a', 'g3b', 'g3c', 'g3e'],
      tri: { asic: true, abr: true, ato: false },
      gateStart: new Map([['g1', daysAgo(9)], ['g3', daysAgo(6)]]),
      notes: {
        background:
          'Interstate line-haul, 4 trucks, ~$1.8M revenue, quarterly GST. Left previous accountant over slow BAS turnaround.',
        atoPosition: '2 BAS outstanding (Dec, Mar). Payment plan on ICA — $14,200 remaining.',
      },
      log: [
        { text: 'Entity created — package: Company', at: daysAgo(9) },
        { text: 'Gate 1 cleared by Sales', at: daysAgo(8) },
        { text: 'Gate 2 cleared — AML complete, risk: medium', at: daysAgo(6) },
        { text: 'Address mismatch found — ATO still shows old Tarneit address', at: daysAgo(2) },
      ],
    },
    {
      name: 'Gill Bros Concreting Pty Ltd',
      track: 'renewal',
      pkg: 'Company',
      managerName: pick(4),
      createdAt: daysAgo(2),
      contact: {
        person: 'Manpreet Gill',
        phone: '0412 335 678',
        email: 'manpreet@gillbros.com.au',
      },
      done: ['r1a', 'r1b', 'r2a'],
      tri: { asic: false, abr: false, ato: false },
      gateStart: new Map([['r1', daysAgo(2)], ['r2', daysAgo(1)]]),
      notes: {
        background: 'Existing client since FY24. Residential concreting, 3 staff.',
        atoPosition: '',
      },
      log: [
        { text: 'Renewal opened — FY2026-27', at: daysAgo(2) },
        { text: 'Gate 1 cleared — renewal signed', at: daysAgo(1) },
      ],
    },
    {
      name: 'BrickWorks Renovations Pty Ltd',
      track: 'new',
      pkg: 'Company',
      managerName: pick(2),
      createdAt: daysAgo(13),
      contact: {
        person: 'Tony Marino',
        phone: '0438 006 172',
        email: 'tony@brickworksreno.com.au',
      },
      done: [...allThrough(4), 'g5a', 'g5b'],
      tri: { asic: true, abr: true, ato: true },
      gateStart: new Map([['g1', daysAgo(13)], ['g5', daysAgo(1)]]),
      notes: {
        background:
          'Domestic renos + small commercial fit-outs. 6 staff, ~$2.4M revenue, monthly IAS. Referral from Manan.',
        atoPosition: 'All lodgements current. No debt.',
      },
      log: [
        { text: 'Entity created — package: Company', at: daysAgo(13) },
        { text: 'Gate 3 cleared — three-way address match confirmed', at: daysAgo(5) },
        { text: 'Gate 4 cleared — handed to Aditya for review', at: daysAgo(1) },
      ],
    },
  ];

  for (const s of seeds) {
    const resolved = await cmSvc.resolveManager(null, s.managerName);
    await OnboardingEntity.create({
      ...s,
      managerId: resolved.managerId,
      managerName: resolved.managerName,
      status: 'active',
      handoverPack: '',
      createdBy: user._id,
    });
  }

  return { seeded: seeds.length };
}

module.exports = {
  getMeta,
  getDashboard,
  listEntities,
  getEntity,
  createEntity,
  updateEntity,
  searchClients,
  getManagerFiles,
  seedOnboarding,
  buildHandoverPack,
  enrichEntity,
};
